version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: "disabled"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: "disabled"

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    rebase-strategy: "disabled"
    groups:
      rails-bundler-security:
        patterns:
          - "rack"
          - "rack-session"
      observability-dev:
        patterns:
          - "bullet"
      analytics-time:
        patterns:
          - "groupdate"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: "disabled"
    groups:
      build-tooling:
        patterns:
          - "esbuild"
          - "postcss*"
          - "sass"
      hotwire-front:
        patterns:
          - "@hotwired/*"
    ignore:
      - dependency-name: "esbuild"
        update-types: ["version-update:semver-major"]
