exclude = [
    "venv/**",
    "**/node_modules/**",
    "**/*.txt",
    "**/*.mdc",
    "**/*.tpl.md",
    "**/CHANGELOG.md",
    "target/**",
    "megalinter-reports/**",
]
validate = true
number = true
wrap = "no"
end_of_line = "lf"

[plugin.mkdocs]
align_semantic_breaks_in_lists = true
ignore_missing_references = true
