[tools]
actionlint        = "1.7.10"
bun               = "1.3.6"
docker-compose    = "5.0.1"
git-cliff         = "2.11.0"
just              = "latest"
markdownlint-cli2 = "0.20.0"
oxlint            = "1.16.0"
pre-commit        = "4.5.1"
ruby              = "3.4.5"
vale              = "3.13.0"
