[tools]

claude-code = { version = "latest", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-x64/claude"

[windows-x64]
bin = "claude.exe"
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/win32-x64/claude.exe"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/latest" }

python            = "3.13"
actionlint        = "1.7.10"
bun               = "1.3.6"
docker-cli        = "29.1.5"
docker-compose    = "5.0.1"
"gem:rails"       = "8.1.2"
git-cliff         = "2.11.0"
just              = "latest"
markdownlint-cli2 = "0.20.0"
oxlint            = "1.16.0"
pre-commit        = "4.5.1"
vale              = "3.13.0"
"gem:rubocop"     = "latest"

[settings]
idiomatic_version_file_enable_tools = [ "ruby", "bun", "python" ]
