[tools]

python            = "3.14"
actionlint        = "1.7.11"
bun               = "1.3.9"
docker-cli        = "29.2.1"
docker-compose    = "5.0.2"
"gem:rails"       = "8.1.2"
git-cliff         = "2.12.0"
just              = "latest"
markdownlint-cli2 = "0.21.0"
oxlint            = "1.49.0"
pre-commit        = "4.5.1"
vale              = "3.13.1"
"gem:rubocop"     = "latest"
vacuum = "0.23.8"

[settings]
idiomatic_version_file_enable_tools = [ "ruby", "bun", "python" ]
